SQLALCHEMY_DATABASE_URI = 'sqlite:////home/miroslav/Source/blog/instance/blog.db'
FLASK_ADMIN_SWITCH = 'cerulean'
FLATPAGES_ROOT = '/home/miroslav/Source/blog/articles/'
FLATPAGES_AUTO_RELOAD = 'DEBUG'
FLATPAGES_EXTENSION = '.md'
